package com.sdt;

public class Common {
    public static final String ACTION_USB_PERMISSION = "com.android.USB_PERMISSION";
    int SUCCESS;
    int EOPEN;
    int ETIMEOUT;
    int EPCCRC;
    int EUSBCONFIG;
    int ECOMFORBIDUSE;
    int EUSBFORBIDUSE;
    int ERR_OPEN_FILE;
    int ESAMCRC;
    int ESAMTIME;
    int EUSBMANAGER;
    int EUSBDEVICENOFOUND;
    int EUSBCONNECTION;
    int ENOUSBRIGHT;
    int ENOUSBINTERFACE;
    int ENORMAL;
    int EPATH;
    int ENOOPEN;
    int ECOMSET;
    int ECLOSE;
    int EPARA;
    int ECOMREAD;
    int ECOMWRITE;
    int EUSBREAD;
    int EUSBWRITE;
    int EDATALEN;
    int EDATAFORMAT;
    int EAPI;
    int EUSBPATH;
    int EMSGLEVEL;
    int EWRITELOG;
    int EOPENLOG;
    int FILENAMELEN;
    int FULLPATHLEN;
    int MAX_RECVLEN;
    int TIME1;
    int TIME2;
    int TIME3;
    int RECVTIMEOUT;
    int IIN_LEN;
    int SN_LEN;
    int MAX_MSG_LEVEL;
    int LOG_NONE;
    int LOG_ERR;
    int LOG_WARN;
    int LOG_INFO;
    int LOG_DBG;
    int SAMID_LEN;

    public Common() {
        this.SUCCESS = 144;
        this.EOPEN = 1;
        this.ETIMEOUT = 2;
        this.EPCCRC = 3;
        this.EUSBCONFIG = 4;
        this.ECOMFORBIDUSE = 5;
        this.EUSBFORBIDUSE = 6;
        this.ERR_OPEN_FILE = 9;
        this.ESAMCRC = 16;
        this.ESAMTIME = 17;
        this.EUSBMANAGER = 18;
        this.EUSBDEVICENOFOUND = 19;
        this.EUSBCONNECTION = 20;
        this.ENOUSBRIGHT = 21;
        this.ENOUSBINTERFACE = 22;
        this.ENORMAL = 400;
        this.EPATH = 401;
        this.ENOOPEN = 402;
        this.ECOMSET = 403;
        this.ECLOSE = 404;
        this.EPARA = 512;
        this.ECOMREAD = 513;
        this.ECOMWRITE = 514;
        this.EUSBREAD = 515;
        this.EUSBWRITE = 516;
        this.EDATALEN = 522;
        this.EDATAFORMAT = 523;
        this.EAPI = 524;
        this.EUSBPATH = 525;
        this.EMSGLEVEL = 526;
        this.EWRITELOG = 527;
        this.EOPENLOG = 528;
        this.FILENAMELEN = 24;
        this.FULLPATHLEN = 256;
        this.MAX_RECVLEN = 3072;
        this.TIME1 = 2;
        this.TIME2 = 5;
        this.TIME3 = 15;
        this.RECVTIMEOUT = 10;
        this.IIN_LEN = 4;
        this.SN_LEN = 8;
        this.MAX_MSG_LEVEL = 5;
        this.LOG_NONE = 0;
        this.LOG_ERR = 1;
        this.LOG_WARN = 2;
        this.LOG_INFO = 3;
        this.LOG_DBG = 4;
        this.SAMID_LEN = 16;
    }
}
