package org.zz.protocol;

public class MXCommand
{
    public static final byte CMD_ID_READ = 21;
    public static final byte CMD_ID_DOOR_CONTROL = 22;
    public static int VENDORID;
    public static int PRODUCTID;
    public static int CMD_TIMEOUT;
    public static int CMD_ID_DOOR_CONTROL_TIMEOUT;
    public static byte CMD_REQ_FLAG;
    public static byte CMD_RET_FLAG;
    public static byte CMD_LED_CONTROL;
    public static byte CMD_DEV_UPDATE;
    public static byte CMD_DEV_RESET;
    public static byte CMD_START_FPC;
    public static byte CMD_CHECK_FPC;
    public static byte CMD_GET_IMAGE;
    public static byte CMD_STOP_FPC;
    public static byte CMD_READ_VERSION;
    public static byte CMD_GET_AUTO_IMAGE;
    public static byte CMD_GET_AUTO_IMAGE_OC;
    public static byte CMD_SetSleepMode;
    public static byte CMD_GET_IMAGE_ANDROID;
    public static byte CMD_GET_PACK_ANDROID;
    public static byte CMD_82_IMAGE;
    public static byte CMD_82_GENTZ;
    public static byte CMD_82_UPTZ;
    public static byte CMD_82_DOWNTZ;
    public static byte CMD_82_DOWNDATA;
    public static byte CMD_82_MATCH;
    public static byte CMD_82_SEARCH;
    public static byte CMD_82_COUNT;
    public static byte CMD_82_DEL_TZ;
    public static byte CMD_82_CLEAR_TZ;
    public static byte CMD_PLAY_VOICE;
    public static byte CMD_SET_SERIAL_NO;
    public static byte CMD_GET_SERIAL_NO;
    public static byte CMD_ZX_GEN_TZ;
    public static byte CMD_RSA_DOWN;
    public static byte CMD_ZX_GET_TZ;
    public static byte CMD_ZX_GET_ENCRY_TZ;
    public static byte CMD_ZX_GET_MB;
    public static byte CMD_ZX_RSA_ENCRY;
    public static int LED_RED_LIGHT;
    public static int LED_GREEN_LIGHT;
    public static int LED_ON;
    public static int LED_OFF;
    
    static {
        MXCommand.VENDORID = 33307;
        MXCommand.PRODUCTID = 514;
        MXCommand.CMD_TIMEOUT = 1000;
        MXCommand.CMD_ID_DOOR_CONTROL_TIMEOUT = 1500;
        MXCommand.CMD_REQ_FLAG = -120;
        MXCommand.CMD_RET_FLAG = -86;
        MXCommand.CMD_LED_CONTROL = 2;
        MXCommand.CMD_DEV_UPDATE = 5;
        MXCommand.CMD_DEV_RESET = 118;
        MXCommand.CMD_START_FPC = 8;
        MXCommand.CMD_CHECK_FPC = 9;
        MXCommand.CMD_GET_IMAGE = 10;
        MXCommand.CMD_STOP_FPC = 12;
        MXCommand.CMD_READ_VERSION = 13;
        MXCommand.CMD_GET_AUTO_IMAGE = 64;
        MXCommand.CMD_GET_AUTO_IMAGE_OC = 69;
        MXCommand.CMD_SetSleepMode = 73;
        MXCommand.CMD_GET_IMAGE_ANDROID = 15;
        MXCommand.CMD_GET_PACK_ANDROID = 7;
        MXCommand.CMD_82_IMAGE = 73;
        MXCommand.CMD_82_GENTZ = 80;
        MXCommand.CMD_82_UPTZ = 81;
        MXCommand.CMD_82_DOWNTZ = 82;
        MXCommand.CMD_82_DOWNDATA = 83;
        MXCommand.CMD_82_MATCH = 84;
        MXCommand.CMD_82_SEARCH = 85;
        MXCommand.CMD_82_COUNT = 86;
        MXCommand.CMD_82_DEL_TZ = 87;
        MXCommand.CMD_82_CLEAR_TZ = 88;
        MXCommand.CMD_PLAY_VOICE = 89;
        MXCommand.CMD_SET_SERIAL_NO = -95;
        MXCommand.CMD_GET_SERIAL_NO = -94;
        MXCommand.CMD_ZX_GEN_TZ = 91;
        MXCommand.CMD_RSA_DOWN = 104;
        MXCommand.CMD_ZX_GET_TZ = 105;
        MXCommand.CMD_ZX_GET_ENCRY_TZ = 106;
        MXCommand.CMD_ZX_GET_MB = 107;
        MXCommand.CMD_ZX_RSA_ENCRY = 108;
        MXCommand.LED_RED_LIGHT = 1;
        MXCommand.LED_GREEN_LIGHT = 2;
        MXCommand.LED_ON = 1;
        MXCommand.LED_OFF = 0;
    }
}
